### ISSUE TITLE
Cannot find module 'styled-components/lib/models/StyleSheet' from 'utils.js'

### ISSUE THREAD

**Issue by vadivelkindhealth** [styled-components/jest-styled-components#115]
I'm using `jest-styled-components: 4.10.0` and when I run `jest`. I get the below.
```js
 FAIL  src/components/Button/tests/index.test.js
  ● Test suite failed to run

    Cannot find module 'styled-components/lib/models/StyleSheet' from 'utils.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:194:17)
      at Object.<anonymous> (../../node_modules/jest-styled-components/src/utils.js:3:20)
```
```js
index.test.js does only a plain import as below.
import 'jest-styled-components';
```
We're using a mono-repo setup with yarn workspaces btw.

Can you help us identify the issue? Please let me know if you need anything further to debug the issue. Thanks!

**Comment by philpl** [comment]
https://github.com/styled-components/jest-styled-components/issues/112
