### ISSUE TITLE
@supports feature query error

### ISSUE THREAD

**Issue by csabbee** [styled-components/jest-styled-components#193]
It seems that if you are using @supports feature query in styled components it will generate the following error when you run your test and render your component:

```
Error: Could not parse CSS stylesheet
    at exports.createStylesheet (/Users/tmp/projects/next-renderer/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:35:21)
    at HTMLStyleElementImpl._updateAStyleBlock (/Users/tmp/projects/next-renderer/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:67:5)
    at HTMLStyleElementImpl._childTextContentChangeSteps (/Users/tmp/projects/next-renderer/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:36:12)
    at TextImpl.replaceData (/Users/tmp/projects/next-renderer/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:73:23)
    at TextImpl.appendData (/Users/tmp/projects/next-renderer/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:43:10)
    at Text.appendData (/Users/tmp/projects/next-renderer/node_modules/jsdom/lib/jsdom/living/generated/CharacterData.js:76:21)
    at Object.insertRules (/Users/tmp/projects/next-renderer/node_modules/styled-components/dist/styled-components.cjs.js:699:16)
    at StyleSheet.inject (/Users/tmp/projects/next-renderer/node_modules/styled-components/dist/styled-components.cjs.js:1131:9)
    at ComponentStyle.generateAndInjectStyles (/Users/tmp/projects/next-renderer/node_modules/styled-components/dist/styled-components.cjs.js:1998:20)
    at StyledComponent.generateAndInjectStyles (/Users/tmp/projects/next-renderer/node_modules/styled-components/dist/styled-components.cjs.js:1693:40) 
```

The funny thing is that the test is passing. Just the console is filled with the generates css.

**Comment by MicheleBertoli** [comment]
Closing due to inactivity.
