### ISSUE TITLE
Error in Jest test when calling toHaveStyleRule

### ISSUE THREAD

**Issue by robowen5mac** [styled-components/jest-styled-components#224]
I have encountered an issue that I think is specific to my current setup, but any help you could provide would be appreciate. If I do the following in a CRA based application, everything works as expected and I can use the custom Jest matchers from jest-styled-components

```
describe("Verify UI state based on jobs", () => {
  afterEach(() => {
    cleanup();
  });
  it('entered id disables other tabs and callback called', async () => {
    let { container } = render(<App />);

    expect(container).toHaveStyleRule('color', 'red');
  });
});

const Component = props => {
  return <div className={props.className}>{props.children}</div>;
};

const StyledComponent = styled(Component)`
  color: ${props => (props.color ? props.color : 'blue')};
`;

class App extends React.Component {
  render() {
    return (
      <div>
        <StyledComponent>Item1</StyledComponent>
        <StyledComponent color="red">Item2</StyledComponent>
      </div>
    );
  }
}
```

However if I try the same thing with a project based off of create-react-library (which has been updated to newer babel and CRA scripts), I get the following when the test runs:

```
undefined:28:49: missing '}'

      103 |     let { container } = render(<App />);
      104 |
    > 105 |     expect(container).toHaveStyleRule('color', 'red');
          |                       ^
      106 |   });
      107 | });
      108 |

      at error (node_modules/css/lib/parse/index.js:62:15)
      at declarations (node_modules/css/lib/parse/index.js:260:26)
      at rule (node_modules/css/lib/parse/index.js:561:21)
      at rules (node_modules/css/lib/parse/index.js:118:70)
      at stylesheet (node_modules/css/lib/parse/index.js:81:21)
      at Object.<anonymous>.module.exports [as parse] (node_modules/css/lib/parse/index.js:565:20)
      at getCSS (node_modules/jest-styled-components/src/utils.js:46:26)
      at Object.toHaveStyleRule (node_modules/jest-styled-components/src/toHaveStyleRule.js:145:15)
      at Object.throwingMatcher (node_modules/expect/build/index.js:320:33)
      at Object.toHaveStyleRule (src/test.js:105:23)
```

Something looks to be wrong with a dependency or configuration, but I am not sure where to start digging to figure out what might be wrong. Any pointers to get me started?

**Comment by robowen5mac** [comment]
Well..I think I figured out the issue, as I was cleaning up some code, I noticed I had a styled component that was missing the closing } on a media query. Was not causing any problems in my application, but there was obviously something that the library is picking up. While correcting that typo didn't fix the issue, it suggests what my problem is and how I need to solve it (just need to find the other subcomponent that has a badly formed style property). Sorry posting the issue, for what is obviously a user issue.

**Comment by nkokla** [comment]
> Sorry posting the issue, for what is obviously a user issue.

Do not be sorry. 
I had a similar error on Jest test without more details. I think you saved my day.
Thank you.
