### ISSUE TITLE
className array throws an error

### ISSUE THREAD

**Issue by KevinSheedy** [styled-components/jest-styled-components#257]
I'm passing an array of classNames to a styled component like this:

```
<ListItem className={['foo', 'bar']} />

const ListItem= styled.li``;
```
Which results in something like this:
`<li class="foo bar" />`

However, when I try to test this using Jest and enzyme, I'm hitting a runtime error:
```
    TypeError: classNameProp.trim is not a function

      15 |
      16 |   it('should render the component correctly', () => {
    > 17 |     expect(shallowComponent).toMatchSnapshot();
         |                              ^
      18 |   });
      19 | });
      20 |

      at getClassNamesFromProps (node_modules/jest-styled-components/src/styleSheetSerializer.js:25:26)
      at nodes.reduce (node_modules/jest-styled-components/src/styleSheetSerializer.js:38:23)
          at Array.reduce (<anonymous>)
      at getClassNames (node_modules/jest-styled-components/src/styleSheetSerializer.js:32:9)
      at Object.print (node_modules/jest-styled-components/src/styleSheetSerializer.js:136:26)
      at printPlugin (node_modules/pretty-format/build/index.js:310:16)
      at printer (node_modules/pretty-format/build/index.js:358:12)
      at plugin.print.valChild (node_modules/pretty-format/build/index.js:312:23)
      at Object.print (node_modules/enzyme-to-json/createSerializer.js:22:14)
      at printPlugin (node_modules/pretty-format/build/index.js:310:16)
      at prettyFormat (node_modules/pretty-format/build/index.js:526:16)
      at Object.throwingMatcher (node_modules/expect/build/index.js:342:33)
      at Object.toMatchSnapshot (src/ui/Components/ListItem/ListItem.test.js:17:30)
```

It looks like styled-components accepts arrays to the className prop. However, jest-styled-components does not.

**Comment by quantizor** [comment]
**Correction:** The null/undefined children fix in v7.3.0 guards against falsy nodes in the component tree, which is a different issue from className being an array. Looking at the serializer code, `getClassNames` handles className via `node.props.className`, and if className is an array instead of a string, it would need separate handling.

If you're still seeing crashes when className is an array on v7.3.0, please reopen with a reproduction.
