### ISSUE TITLE
Error returned when using toHaveStyleRule

### ISSUE THREAD

**Issue by gavin-johnson84** [styled-components/jest-styled-components#32]
Hi, I'm hoping someone can help me with a problem I'm having with my tests.

Each time I run the following test:
```
import React from 'react';
import { shallow } from 'enzyme';
import 'jest-styled-components';

import CreateButton from './';
import LinkButton from './CreateButton.styles';

describe('CreateButton', () => {
  const stateKey = 'create';
  const navigationData = { client: 'client' };
  const text = 'Create Campaign';
  const color = 'red';
  let component;

  beforeEach(() => {
    component = shallow(
      <CreateButton
        stateKey={stateKey}
        navigationData={navigationData}
        text={text}
      />
    );
  });

  it('should render correctly', () => {
    expect(component).toMatchSnapshot();
  });

  it('should have a LinkButton component', () => {
    expect(component.find(LinkButton)).toHaveLength(1);
  });

  it('should have correct Text component', () => {
    const props = component.find(LinkButton).props();
    expect(props.stateKey).toBe(stateKey);
    expect(props.navigationData).toBe(navigationData);
    expect(props.text).toBe(text);
  });

  it('should display the correct colour', () => {
    component = shallow(
      <LinkButton
        stateKey={stateKey}
        navigationData={navigationData}
        text={text}
        theme={{ buttonText: color }}
      />
    );
    expect(component).toMatchStyledComponentsSnapshot();
    expect(component).toHaveStyleRule('color', color);
  });
});
```

I receive this error:
```
  ● CreateButton › should display the correct colour

    
            "Expected [object Object] to be a component from react-test-renderer, or a mounted enzyme component."
    
            "But had an error, TypeError: Cannot read property '_renderedComponent' of undefined"
      
            
      at Object.<anonymous> (src/components/CreateButton/CreateButton.tests.js:50:23)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

Here's what the component I'm attempting to test looks like:
```
import styled from 'styled-components';

import { LinkButton } from 'tetris-blocks';

export default styled(LinkButton)`
  width: 170px;
  height: 40px;
  font-size: 0.95em;
  color: ${({ theme }) => theme.buttonText};
`;
```

Please also see the snapshot file I'm using below:
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`CreateButton should display the correct colour 1`] = `
.iHrtRh {
  width: 170px;
  height: 40px;
  font-size: 0.95em;
  color: red;
}

<LinkButton
  className="sc-htpNat iHrtRh"
  navigationData={
    Object {
      "client": "client",
    }
  }
  stateKey="create"
  text="Create Campaign"
  theme={
    Object {
      "buttonText": "red",
    }
  }
/>
`;

exports[`CreateButton should render correctly 1`] = `
<Styled(LinkButton)
  navigationData={
    Object {
      "client": "client",
    }
  }
  stateKey="create"
  text="Create Campaign"
/>
`;
```

A couple of us have reviewed this now and can't reach a conclusion as to what's causing the problem, but after commenting out the following `expect(component).toHaveStyleRule('color', color);` from the test it passes. Which has led us to believe there could be a problem with the package.

I'm using currently using version `3.0.2` of the package.

Many thanks and apologies for all the code snippets!

**Comment by MicheleBertoli** [comment]
Thanks for opening the issue @gavin-johnson84, it's fixed in v3.1.0.
