### ISSUE TITLE
Could neither find styled-components secret internals

### ISSUE THREAD

**Issue by thomasdittmar** [styled-components/jest-styled-components#359]
Hi all,

I know that this issue has been posted before and the solution was to update the library but I even with the newer version I see that error while by just importing `import 'jest-styled-components'`

Here are the installed versions:
```javascript
"react": "16.13.1",
"react-native": "0.63.1",
"styled-components": "5.2.1"
"jest-styled-components": "7.0.2",
```

My Test:
```javascript
import React from 'react'
import { create } from 'react-test-renderer'
import 'jest-styled-components'

import { Box } from '../components/Box'

describe('Box component', () => {
  test('Matches the snapshot', () => {
    const button = create(
      <Box />
    )
    expect(button.toJSON()).toMatchSnapshot()
  })
})
```

Error:
```javascript
● Test suite failed to run

    Could neither find styled-components secret internals

      at Object.<anonymous> (node_modules/jest-styled-components/src/utils.js:5:9)
      at Object.<anonymous> (node_modules/jest-styled-components/src/index.js:5:19)
```

Is there a work-around for that issue? I really need to `Snapshot` my components urgently!

Thanks

**Comment by JTMCaplin** [comment]
Did you ever find an answer for this? Having the same problem

**Comment by Justin2997** [comment]
Have the same setup and same problem :(

**Comment by eduardomarr** [comment]
same error here!!

**Comment by fsjsd** [comment]
same

**Comment by maksim-romanov** [comment]
same issue for me

**Comment by GabrielDierks** [comment]
Same here.

```
    "react-test-renderer": "18.2.0",
    "react-native": "0.74.5",

    "jest": "^29.4.0",
    "jest-expo": "^51.0.0",
    "jest-styled-components": "^7.2.0",
    "styled-components": "6.1.11",
    "babel-plugin-styled-components": "^2.1.4",
```
