### ISSUE TITLE
v7.0.5 does not work on node v10

### ISSUE THREAD

**Issue by Lokua** [styled-components/jest-styled-components#383]
Today we noticed that all of our snapshots are failing from version 7.0.5 on a box running Node 10 (which does not support flatMap).

```sh
FAIL  src/InlineNotification/__tests__/InlineNotification.spec.js
  ● InlineNotification › should render Info variant by default

    TypeError: selectors.flatMap is not a function

       8 |       <InlineNotification>important stuff</InlineNotification>
       9 |     )
    > 10 |     expect(component.toJSON()).toMatchSnapshot()
         |                                ^
      11 |   })
      12 | })
      13 |

      at includesUnknownClassNames (node_modules/jest-styled-components/src/styleSheetSerializer.js:55:6)
      at node_modules/jest-styled-components/src/styleSheetSerializer.js:61:4
          at Array.filter (<anonymous>)
      at getStyle (node_modules/jest-styled-components/src/styleSheetSerializer.js:77:38)
      at Object.print (node_modules/jest-styled-components/src/styleSheetSerializer.js:135:19)
      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:386:30)
      at Object.toMatchSnapshot (node_modules/expect/build/index.js:387:15)
      at Object.<anonymous> (src/InlineNotification/__tests__/InlineNotification.spec.js:10:32)
```

Downgrading to 7.0.4 fixes the issue. Just thought it worth bringing up and understand if Node 10 is too old to support.

**Comment by probablyup** [comment]
Thanks for the note, Node 10 has fallen out of security updates so we aren't supporting it here either. I'll add an "engines" field to make this more obvious

**Comment by probablyup** [comment]
Actually I just checked and "engines" was added in the prior release. Apologies, that should have been a major version bump in retrospect. Node 12+ will work as expected.
