### ISSUE TITLE
toHaveStyleRule property not found

### ISSUE THREAD

**Issue by wagg-matt** [styled-components/jest-styled-components#87]
Hey,

I'm aware this may be an oversight on my part and not a bug but any help would be greatly appreciated.

First time using `jest-styled-components` and cannot get a test to work using `toHaveStyleRule`, including the examples. I would like to test if a `Button` has a `warning` prop, this is replicated in the styles.

package.json
```
{
  "name": "ui-components",
  "version": "0.0.0",
  "description": "UI components monorepo",
  "devDependencies": {
    "@kadira/storybook": "^2.21.0",
    "babel-cli": "^6.26.0",
    "babel-jest": "^21.2.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "enzyme": "^3.1.0",
    "enzyme-adapter-react-15": "^1.0.2",
    "glob-loader": "^0.3.0",
    "jest": "^21.2.1",
    "jest-styled-components": "^4.9.0",
    "lerna": "^2.4.0",
    "react-scripts": "0.8.5",
    "react-test-renderer": "15.4.0"
  },
  "jest": {
    "setupTestFrameworkScriptFile": "<rootDir>/tests/config.js",
    "resetModules": true,
    "resetMocks": true,
    "collectCoverage": true,
    "collectCoverageFrom": [
      "packages/**/**/*.js",
      "!packages/**/dist/**",
      "!**/node_modules/**",
      "!**/**/*story.js"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 100,
        "functions": 100,
        "lines": 100,
        "statements": 100
      }
    },
    "coverageReporters": [
      "lcov",
      "html"
    ],
    "coveragePathIgnorePatterns": [
      "<rootDir>node_modules/",
      "<rootDir?coverage/"
    ],
    "testMatch": [
      "**/**/?(*.)(spec).js?(x)"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>node_modules/"
    ],
    "transformIgnorePatterns": [
      "<rootDir>node_modules/"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "dependencies": {
    "prop-types": "^15.6.0",
    "react": "^15.6.2",
    "react-dom": "^15.6.2",
    "react-router": "^3.2.0",
    "styled-components": "^2.2.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "storybook": "NODE_ENV=development start-storybook -p 4005 -c .storybook",
    "test": "jest --coverage --verbose",
    "build-storybook": "build-storybook -s .storybook",
    "coverage-report": "http-server coverage -p4005"
  }
}

```
component
```
import React from 'react';
import PropTypes from 'prop-types';

import StyledButton from './styledComponents/styledButton';

const Button = ({
  children, onClick, warning,
  fullwidth, outline, tertiary,
  text, buttonLink, white,
}) => (
  <StyledButton
    warning={warning}
    fullwidth={fullwidth}
    outline={outline}
    tertiary={tertiary}
    text={text}
    buttonLink={buttonLink}
    white={white}
    onClick={onClick}
  >
    {children}
  </StyledButton>
);

Button.propTypes = {
  children: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.element,
  ]),
  onClick: PropTypes.func,
  warning: PropTypes.bool,
  fullwidth: PropTypes.bool,
  outline: PropTypes.bool,
  tertiary: PropTypes.bool,
  text: PropTypes.bool,
  buttonLink: PropTypes.bool,
  white: PropTypes.bool,
};

export default Button;
```
styled-component
```
import styled from 'styled-components';

import Colors from '../../Colors';

const styledButton = styled.div`
  /* Adapt the colors based on primary prop */
  ${props => props.warning ? `background-color: ${Colors.warning};` : `background-color: ${Colors.greenyBlue};`}
  ${props => props.outline || props.tertiary || props.text ? 'background-color: transparent;' : null};
  ${props => props.outline ? `box-shadow: inset 0px 0px 0px 2px ${Colors.greenyBlue}` : null};
  ${props => props.tertiary ? `box-shadow: inset 0px 0px 0px 2px ${Colors.darkerGreen}` : null};
  ${props => !props.text ? 'border-radius: 24px; border: none;' : null};
  color: ${props => props.white ? Colors.greenyBlue : Colors.white};
  cursor: pointer;
  display: inline-block;
  font-family: Raleway, sans-serif;
  font-size: 14px;
  font-weight: 800;
  letter-spacing: 1px;
  line-height: 1em;
  margin: 0;
  ${props => !props.text ? 'padding: 14px 20px;' : 'padding: 0 0 3px; border-bottom: 2px solid transparent;'};
  ${props => !props.text && props.buttonLink ? 'padding: 0;' : null};
  text-align: center;
  text-transform: uppercase;
  ${props => props.outline || props.tertiary || props.text ? 'transition: 300ms;' : 'transition: background-color 300ms;'};
  ${props => props.fullwidth ? 'width: calc(100% - 40px);' : null};

  a {
    color: inherit;
    display: block;
    ${props => !props.text ? 'padding: 14px 20px;' : null};
    text-decoration: inherit;
  }

  &:hover {
    ${props => !props.outline ? `background-color: ${Colors.greenHover};` : `box-shadow: inset 0px 0px 0px 3px ${Colors.greenyBlue};`};
    ${props => props.tertiary ? `background-color: transparent; box-shadow: inset 0px 0px 0px 3px ${Colors.darkerGreen};` : null};
    ${props => props.warning ? `background-color: ${Colors.warningHover};` : null};
    ${props => props.outline || props.tertiary || props.text ? 'transition: box-shadow 300ms;' : 'transition: background-color 300ms;'};
    ${props => props.text ? 'background-color: transparent; border-bottom: 2px solid #fff' : null};
    ${props => props.text && props.white ? `border-bottom: 2px solid ${Colors.greenyBlue}` : null};
  }
`;

export default styledButton;
```
tests
```
import React from 'react';
import { mount, shallow } from 'enzyme';
import styled from 'styled-components';
import renderer from 'react-test-renderer';
import 'jest-styled-components';

import Colors from '../Colors';

import Button from '.';
import styledButton from './styledComponents/styledButton';

const Parent = styled.div`
  color: red;
`;

describe('Button Component', function () {
  it('renders children when passed in', () => {
    const wrapper = mount((
      <Button>
        <p className="childProp">A child prop</p>
      </Button>
    ));

    const child = wrapper.find('.childProp');
    expect(child.length).toBe(1);
  });

  it('handles onClick events', () => {
    const onClick = jest.fn();
    const wrapper = mount((
      <Button className="button" onClick={onClick} />
    ));

    wrapper.find('.button').simulate('click');
    expect(onClick.mock.calls.length).toBe(1);
  });

  it('renders a warning button', () => {
    const tree = shallow(<Button warning>Warning Button</Button>);
    console.log(tree.find(styledButton).debug());
    expect(tree.find(styledButton)).toHaveStyleRule('background-color', Colors.warning);
  });

  it('test', () => {
    const wrapper = mount(<Parent />);
    console.log(wrapper.debug());
    expect(wrapper).toHaveStyleRule('color', 'red');
  });
});
```

The test I am trying to get to work is `renders a warning button` and the last test is another test that I have used, simply to try and see if I can get it to work. The output is as follows:
```
 FAIL  packages/atoms/src/Button/index.spec.js
  Button Component
    ✓ renders children when passed in (65ms)
    ✓ handles onClick events (14ms)
    ✕ renders a warning button (29ms)
    ✕ test (9ms)

  ● Button Component › renders a warning button

    Property not found: "background-color"
      
      at Object.<anonymous> (packages/atoms/src/Button/index.spec.js:41:47)
          at Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

  ● Button Component › test

    Property not found: "color"
      
      at Object.<anonymous> (packages/atoms/src/Button/index.spec.js:47:21)
          at Promise (<anonymous>)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:169:7)

  console.log packages/atoms/src/Button/index.spec.js:40
    <styled.div warning={true} fullwidth={[undefined]} outline={[undefined]} tertiary={[undefined]} text={[undefined]} buttonLink={[undefined]} white={[undefined]} onClick={[undefined]}>
      Warning Button
    </styled.div>

  console.log packages/atoms/src/Button/index.spec.js:46
    <styled.div>
      <div className="sc-bwzfXH bukUYK" />
    </styled.div>

```

If anymore info is helpful, please let me know. Have had a good read through the docs, issues and tried to replicate examples that have worked to no avail.

Any help is greatly appreciated.

Thanks
Matt

**Comment by MicheleBertoli** [comment]
Hello @wagg-matt,
I copy/pasted your code and it works:

<img width="425" alt="screen shot 2017-10-24 at 9 49 52 am" src="https://user-images.githubusercontent.com/1308971/31956605-c59d92c2-b8a0-11e7-9f46-e7879ee3ed75.png">

If you'd be able to provide a full non-working repo, I could try and look into it.
Thank you very much!

**Comment by wagg-matt** [comment]
@MicheleBertoli i'll take a further look. Thanks so much for having a look, much appreciated.
